[package]
edition = "2021"
name = "p06_aimd_semaphore"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec", "io"] }
anyhow = "1"
futures = "0.3"
